/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.Conexion;
import IO.CodigoDeVelocidad;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class FrmCodigoDeVelocidad extends javax.swing.JFrame {

    ArrayList<CodigoDeVelocidad> lista = new ArrayList<CodigoDeVelocidad>();

    DefaultListModel modelo = new DefaultListModel();
    private final JFrame hola;

    /**
     * Creates new form FrmEmpleado
     *
     * @param hola
     */
    public FrmCodigoDeVelocidad(JFrame hola) {
        initComponents();

        cerrar();

        cargar();

        this.setLocationRelativeTo(null);

        Iterator<IO.CodigoDeVelocidad> ItCodigoDeVelocidad = Conexion.getInstance().getCodigoDeVelocidades().ListCodigoDeVelocidad().iterator();

        while (ItCodigoDeVelocidad.hasNext()) {

            modelo.addElement(ItCodigoDeVelocidad.next());
        }
        this.hola = hola;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCodigoMemoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtKmHMemoria = new javax.swing.JTextField();
        jBtnGuardarEnTabla = new javax.swing.JButton();
        jBtnActualizarMemoria = new javax.swing.JButton();
        jBtnLimpiarMemoria = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblMemoria = new javax.swing.JTable();
        jBtnEliminarFilaMemoria = new javax.swing.JButton();
        jBtnEliminarTodoMemoria = new javax.swing.JButton();
        jBtnGuardarEnBaseDeDato = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBaseDeDatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jBtnActualizarBaseDeDatos = new javax.swing.JButton();
        jTxtKmHBaseDeDatos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/KmH.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 67, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Codigo De Velocidad (KM/H)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jTxtCodigoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtCodigoMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoMemoriaKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtCodigoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 152, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("KM/H:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jTxtKmHMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtKmHMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtKmHMemoriaKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtKmHMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 152, -1));

        jBtnGuardarEnTabla.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardarEnTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardarEnTabla.setText("Guardar en la tabla");
        jBtnGuardarEnTabla.setBorderPainted(false);
        jBtnGuardarEnTabla.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarEnTablaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardarEnTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 222, 33));

        jBtnActualizarMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarMemoria.setText("Actualizar");
        jBtnActualizarMemoria.setBorderPainted(false);
        jBtnActualizarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnActualizarMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 222, 33));

        jBtnLimpiarMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnLimpiarMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        jBtnLimpiarMemoria.setText("Limpiar campos");
        jBtnLimpiarMemoria.setBorderPainted(false);
        jBtnLimpiarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLimpiarMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 222, 33));

        jTblMemoria.setAutoCreateRowSorter(true);
        jTblMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTblMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Km/H"
            }
        ));
        jTblMemoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTblMemoria.setRowSelectionAllowed(false);
        jTblMemoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblMemoriaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblMemoria);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 484, 100));

        jBtnEliminarFilaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarFilaMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarFilaMemoria.setText("Eliminar fila");
        jBtnEliminarFilaMemoria.setBorderPainted(false);
        jBtnEliminarFilaMemoria.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnEliminarFilaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarFilaMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEliminarFilaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 222, 33));

        jBtnEliminarTodoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarTodoMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarTodoMemoria.setText("Eliminar todo");
        jBtnEliminarTodoMemoria.setBorderPainted(false);
        jBtnEliminarTodoMemoria.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnEliminarTodoMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarTodoMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEliminarTodoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 222, 33));

        jBtnGuardarEnBaseDeDato.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardarEnBaseDeDato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardarEnBaseDeDato.setText("Guardar en base de datos");
        jBtnGuardarEnBaseDeDato.setBorderPainted(false);
        jBtnGuardarEnBaseDeDato.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnBaseDeDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarEnBaseDeDatoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardarEnBaseDeDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 222, 33));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 610));

        jTabbedPane1.addTab("Agregar Codigo De Velocidad (KM/H)", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/KmH.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, -1, -1));

        jTblBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTblBaseDeDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Simb.", "Km/H"
            }
        ));
        jTblBaseDeDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblBaseDeDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblBaseDeDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 71, 139, 248));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("CODIGO DE VELOCIDAD (KM/H)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jBtnActualizarBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarBaseDeDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarBaseDeDatos.setText("Actualizar");
        jBtnActualizarBaseDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarBaseDeDatosActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnActualizarBaseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 343, 139, 33));

        jTxtKmHBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtKmHBaseDeDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtKmHBaseDeDatosKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtKmHBaseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 354, 152, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("KM/H:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 360, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jLabel9.setText("jLabel4");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 610));

        jTabbedPane1.addTab("Actualizar Codigo Velocidad (Base De Datos)", jPanel2);

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoMemoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtCodigoMemoriaKeyTyped

    private void jTxtKmHMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtKmHMemoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtKmHMemoriaKeyTyped

    private void jBtnGuardarEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarEnTablaActionPerformed
        // TODO add your handling code here:
        if (jTxtCodigoMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA CODIGO DE VELOCIDAD", "CODIGO", JOptionPane.ERROR_MESSAGE);
            jTxtCodigoMemoria.requestFocus();
        } else if (jTxtKmHMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA KM/H", "KM/H", JOptionPane.ERROR_MESSAGE);
            jTxtKmHMemoria.requestFocus();
        } else {
            IO.CodigoDeVelocidad c = new IO.CodigoDeVelocidad();
            c.setSimbVelocidad(jTxtCodigoMemoria.getText());
            c.setVelocidadKmH(jTxtKmHMemoria.getText());
            lista.add(c);
            mostrar();
            iniPant();
        }
    }//GEN-LAST:event_jBtnGuardarEnTablaActionPerformed

    private void jBtnActualizarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarMemoriaActionPerformed
        // TODO add your handling code here:
        int filaSelec = jTblMemoria.getSelectedRow();
        if (filaSelec >= 0) {
            if (jTxtCodigoMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA CODIGO DE VELOCIDAD", "CODIGO", JOptionPane.ERROR_MESSAGE);
                jTxtCodigoMemoria.requestFocus();
            } else if (jTxtKmHMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA KM/H", "KM/H", JOptionPane.ERROR_MESSAGE);
                jTxtKmHMemoria.requestFocus();
            } else {
                int actualizar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ACTUALIZAR?", "ACTUALIZAR", JOptionPane.YES_NO_OPTION);
                if (actualizar == JOptionPane.YES_OPTION) {
                    IO.CodigoDeVelocidad a = (IO.CodigoDeVelocidad) lista.get(jTblMemoria.getSelectedRow());
                    a.setSimbVelocidad(jTxtCodigoMemoria.getText());
                    a.setVelocidadKmH(jTxtKmHMemoria.getText());
                    mostrar();
                    iniPant();
                } else {
                    jTxtCodigoMemoria.requestFocus();
                    iniPant();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HA SELECCIONADO NINGUNA FILA", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnActualizarMemoriaActionPerformed

    private void jBtnLimpiarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarMemoriaActionPerformed
        // TODO add your handling code here:
        int limpiarCampo = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE LIMPIAR LOS CAMPOS?", "LIMPIAR", JOptionPane.YES_NO_OPTION);
        if (limpiarCampo == JOptionPane.YES_OPTION) {
            iniPant();
        }
    }//GEN-LAST:event_jBtnLimpiarMemoriaActionPerformed

    private void jTblMemoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblMemoriaMouseClicked
        // TODO add your handling code here:
        int seleccion = jTblMemoria.rowAtPoint(evt.getPoint());
        jTxtCodigoMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 0)));
        jTxtKmHMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 1)));
    }//GEN-LAST:event_jTblMemoriaMouseClicked

    private void jBtnEliminarFilaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarFilaMemoriaActionPerformed
        // TODO add your handling code here:
        int filaSelec = jTblMemoria.getSelectedRow();
        if (filaSelec >= 0) {
            int borrarFila = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ELIMINAR LA FILA SELECCIONADA?", "ELIMINAR", JOptionPane.YES_NO_OPTION);
            if (borrarFila == JOptionPane.YES_OPTION) {
                lista.remove(jTblMemoria.getSelectedRow());
                if (jTblMemoria.getSelectedRow() != -1) {
                    DefaultTableModel mdl = (DefaultTableModel) jTblMemoria.getModel();
                    mdl.removeRow(jTblMemoria.getSelectedRow());
                    iniPant();
                    JOptionPane.showMessageDialog(this, "FILA ELIMINADA CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "ELIMINACION CANCELADA");
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HA SELECCIONADO NINGUNA FILA");
        }
    }//GEN-LAST:event_jBtnEliminarFilaMemoriaActionPerformed

    private void jBtnEliminarTodoMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarTodoMemoriaActionPerformed
        // TODO add your handling code here:
        if (jTblMemoria.getRowCount() > 0) {
            int borrarTodo = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ELIMINAR TODO?", "ELIMINAR", JOptionPane.YES_NO_OPTION);
            if (borrarTodo == JOptionPane.YES_OPTION) {
                vaciadoMemoria();
                iniPant();
            }
        }
    }//GEN-LAST:event_jBtnEliminarTodoMemoriaActionPerformed

    private void jBtnGuardarEnBaseDeDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarEnBaseDeDatoActionPerformed
        // TODO add your handling code here:
        if (jTblMemoria.getRowCount() > 0) {
            int guardar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE GUARDAR EN LA BASE DE DATOS?", "GUARDAR", JOptionPane.YES_NO_OPTION);
            if (guardar == JOptionPane.YES_OPTION) {
                for (int i = 0; i < jTblMemoria.getRowCount(); i++) {
                    IO.CodigoDeVelocidad cdv = new IO.CodigoDeVelocidad();
                    cdv.setSimbVelocidad((String) jTblMemoria.getValueAt(i, 0));
                    cdv.setVelocidadKmH((String) jTblMemoria.getValueAt(i, 1));
                    Conexion.getInstance().guardar(cdv);
                }
                JOptionPane.showMessageDialog(this, "A GUARDADO CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                vaciadoBaseDeDatos();
                vaciadoMemoria();
                Iterator<IO.CodigoDeVelocidad> ItCodigoDeVelocidad = Conexion.getInstance().getCodigoDeVelocidades().ListCodigoDeVelocidad().iterator();
                while (ItCodigoDeVelocidad.hasNext()) {
                    modelo.addElement(ItCodigoDeVelocidad.next());
                }
                cargar();
                try{
                    FrmProducto frm = (FrmProducto) hola;
                    frm.cargarCombo();
                    this.dispose();
                }catch(Exception e){
                    
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HAY DATOS EN LA TABLA", "INFIRMACION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnGuardarEnBaseDeDatoActionPerformed

    private void jTblBaseDeDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBaseDeDatosMouseClicked
        // TODO add your handling code here:
        int seleccion = jTblBaseDeDatos.rowAtPoint(evt.getPoint());
        jTxtKmHBaseDeDatos.setText(String.valueOf(jTblBaseDeDatos.getValueAt(seleccion, 1)));
    }//GEN-LAST:event_jTblBaseDeDatosMouseClicked

    private void jBtnActualizarBaseDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarBaseDeDatosActionPerformed
        // TODO add your handling code here:
        if (jTxtKmHBaseDeDatos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA KM/H", "KM/H", JOptionPane.ERROR_MESSAGE);
            jTxtKmHBaseDeDatos.requestFocus();
        } else {
            int actualizar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ACTUALIZAR?", "ACTUALIZAR", JOptionPane.YES_NO_OPTION);
            if (actualizar == JOptionPane.YES_OPTION) {
                IO.CodigoDeVelocidad a = (IO.CodigoDeVelocidad) modelo.get(jTblBaseDeDatos.getSelectedRow());
                a.setVelocidadKmH(jTxtKmHBaseDeDatos.getText());
                Conexion.getInstance().getCodigoDeVelocidades().actualizar(a);
                modelo.remove(jTblBaseDeDatos.getSelectedRow());
                if (jTblBaseDeDatos.getRowCount() > 0) {
                    DefaultTableModel mdl = (DefaultTableModel) jTblBaseDeDatos.getModel();
                    modelo.clear();
                    mdl.setRowCount(0);
                    jTxtKmHBaseDeDatos.setText("");
                    Iterator<IO.CodigoDeVelocidad> ItCodigoDeVelocidad = Conexion.getInstance().getCodigoDeVelocidades().ListCodigoDeVelocidad().iterator();
                    while (ItCodigoDeVelocidad.hasNext()) {
                        modelo.addElement(ItCodigoDeVelocidad.next());
                    }
                    cargar();
                    JOptionPane.showMessageDialog(this, "A ACTUALIZADO CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "ACTUALIZACION CANCELADA");
                jTxtKmHBaseDeDatos.setText("");
            }
        }
    }//GEN-LAST:event_jBtnActualizarBaseDeDatosActionPerformed

    private void jTxtKmHBaseDeDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtKmHBaseDeDatosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtKmHBaseDeDatosKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (jTblMemoria.getRowCount() < 1) {
            int cerrar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE CERRAR?", "CERRAR", JOptionPane.YES_NO_OPTION);
            if (cerrar == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HA GUARDADO EN LA BASE DE DATOS", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
            jBtnGuardarEnBaseDeDato.requestFocus();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void cargar() {
        DefaultTableModel mdl = (DefaultTableModel) jTblBaseDeDatos.getModel();
        Iterator<IO.CodigoDeVelocidad> ItCodigoDeVelocidad = Conexion.getInstance().getCodigoDeVelocidades().ListCodigoDeVelocidad().iterator();
        while (ItCodigoDeVelocidad.hasNext()) {
            Object[] fila = new Object[2];
            CodigoDeVelocidad aux = ItCodigoDeVelocidad.next();
            fila[0] = aux;
            fila[1] = aux.getVelocidadKmH();
            mdl.addRow(fila);
        }
    }

    public void vaciadoMemoria() {
        DefaultTableModel mdl = (DefaultTableModel) jTblMemoria.getModel();
        lista.clear();
        mdl.setRowCount(0);
    }

    public void vaciadoBaseDeDatos() {
        DefaultTableModel mdl = (DefaultTableModel) jTblBaseDeDatos.getModel();
        lista.clear();
        mdl.setRowCount(0);
    }

    public void iniPant() {
        jTxtCodigoMemoria.setText("");
        jTxtKmHMemoria.setText("");
        jTxtCodigoMemoria.requestFocus();
    }

    public void mostrar() {
        String matris[][] = new String[lista.size()][2];
        for (int i = 0; i < lista.size(); i++) {
            matris[i][0] = lista.get(i).getSimbVelocidad();
            matris[i][1] = lista.get(i).getVelocidadKmH();
        }
        jTblMemoria.setModel(new javax.swing.table.DefaultTableModel(
                matris,
                new String[]{
                    "Codigo", "Km/H"
                }
        ));
    }

    public void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            this.setVisible(true);;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void confirmarSalida() {
        if (jTblMemoria.getRowCount() < 1) {
            int cerrar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE CERRAR?", "CERRAR", JOptionPane.YES_NO_OPTION);
            if (cerrar == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HA GUARDADO EN LA BASE DE DATOS", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
            jBtnGuardarEnBaseDeDato.requestFocus();
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmCodigoDeVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmCodigoDeVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmCodigoDeVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmCodigoDeVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmCodigoDeVelocidad().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarBaseDeDatos;
    private javax.swing.JButton jBtnActualizarMemoria;
    private javax.swing.JButton jBtnEliminarFilaMemoria;
    private javax.swing.JButton jBtnEliminarTodoMemoria;
    private javax.swing.JButton jBtnGuardarEnBaseDeDato;
    private javax.swing.JButton jBtnGuardarEnTabla;
    private javax.swing.JButton jBtnLimpiarMemoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblBaseDeDatos;
    private javax.swing.JTable jTblMemoria;
    private javax.swing.JTextField jTxtCodigoMemoria;
    private javax.swing.JTextField jTxtKmHBaseDeDatos;
    private javax.swing.JTextField jTxtKmHMemoria;
    // End of variables declaration//GEN-END:variables
}
