/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class FrmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleado
     */
    public FrmEmpleado() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtCIMemoria = new javax.swing.JTextField();
        jTxtNombreMemoria = new javax.swing.JTextField();
        jTxtApellidoMemoria = new javax.swing.JTextField();
        jTxtTelefonoMemoria = new javax.swing.JTextField();
        jTxtDireccionMemoria = new javax.swing.JTextField();
        jBtnValidaCIMemoria = new javax.swing.JButton();
        jBtnValidaCIMemoria1 = new javax.swing.JButton();
        jBtnActualizarMemoria = new javax.swing.JButton();
        jBtnGuardaEnLaTablar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMemoria = new javax.swing.JTable();
        jBtnEliminarFilaMemoria = new javax.swing.JButton();
        jBtnEliminarTodoMemoria = new javax.swing.JButton();
        jBtnGuardaEnBaseDeDato = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblMemoria1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTxtApellidoMemoria1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtDireccionMemoria1 = new javax.swing.JTextField();
        jBtnActualizarBaseDeDato = new javax.swing.JButton();
        jTxtTelefonoMemoria1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtNombreMemoria1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("C.I:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Direccion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, -1, -1));

        jTxtCIMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtCIMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 86, 150, -1));

        jTxtNombreMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtNombreMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 130, 150, -1));

        jTxtApellidoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtApellidoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 150, -1));

        jTxtTelefonoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtTelefonoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 174, 150, -1));

        jTxtDireccionMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtDireccionMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 150, -1));

        jBtnValidaCIMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnValidaCIMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Validador.png"))); // NOI18N
        jBtnValidaCIMemoria.setText("Valida C.I");
        jBtnValidaCIMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValidaCIMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnValidaCIMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 222, 35));

        jBtnValidaCIMemoria1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnValidaCIMemoria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        jBtnValidaCIMemoria1.setText("Limpiar Campos");
        jBtnValidaCIMemoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValidaCIMemoria1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnValidaCIMemoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 222, 35));

        jBtnActualizarMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarMemoria.setText("Actualizar");
        jBtnActualizarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnActualizarMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 222, 35));

        jBtnGuardaEnLaTablar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardaEnLaTablar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardaEnLaTablar.setText("Guardar en la tabla");
        jBtnGuardaEnLaTablar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardaEnLaTablarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardaEnLaTablar, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 277, 222, 35));

        jTblMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.I", "Nombre", "Apellido", "Telefono", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(jTblMemoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 336, 710, 100));

        jBtnEliminarFilaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarFilaMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarFilaMemoria.setText("Eliminar Fila");
        jBtnEliminarFilaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarFilaMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEliminarFilaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 460, 222, 35));

        jBtnEliminarTodoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarTodoMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarTodoMemoria.setText("Eliminar Fila");
        jBtnEliminarTodoMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarTodoMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEliminarTodoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 222, 35));

        jBtnGuardaEnBaseDeDato.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardaEnBaseDeDato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardaEnBaseDeDato.setText("Guardar en base de datos");
        jBtnGuardaEnBaseDeDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardaEnBaseDeDatoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardaEnBaseDeDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 222, 35));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Empleado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 590));

        jTabbedPane1.addTab("Agregar Empleado", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("Empleado");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jTblMemoria1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "Direccion", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTblMemoria1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 800, 300));

        jTxtApellidoMemoria1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("Apellido:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Direccion:");

        jTxtDireccionMemoria1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jBtnActualizarBaseDeDato.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarBaseDeDato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarBaseDeDato.setText("Actualizar");
        jBtnActualizarBaseDeDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarBaseDeDatoActionPerformed(evt);
            }
        });

        jTxtTelefonoMemoria1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBox1.setText("Activo");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("Telefono:");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Nombre:");

        jTxtNombreMemoria1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(58, 58, 58)
                                .addComponent(jTxtTelefonoMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(63, 63, 63)
                                .addComponent(jTxtNombreMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jCheckBox1)
                        .addGap(377, 377, 377)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtApellidoMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDireccionMemoria1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnActualizarBaseDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtNombreMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtApellidoMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtTelefonoMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDireccionMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jBtnActualizarBaseDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 800, 160));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 610));

        jTabbedPane1.addTab("Actualizar Empleado (Base De Datos)", jPanel2);

        jMenu1.setText("Activo");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardaEnBaseDeDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardaEnBaseDeDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGuardaEnBaseDeDatoActionPerformed

    private void jBtnEliminarTodoMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarTodoMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarTodoMemoriaActionPerformed

    private void jBtnEliminarFilaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarFilaMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarFilaMemoriaActionPerformed

    private void jBtnGuardaEnLaTablarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardaEnLaTablarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGuardaEnLaTablarActionPerformed

    private void jBtnActualizarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnActualizarMemoriaActionPerformed

    private void jBtnValidaCIMemoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValidaCIMemoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnValidaCIMemoria1ActionPerformed

    private void jBtnValidaCIMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValidaCIMemoriaActionPerformed
        // TODO add your handling code here:
        if (jTxtCIMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA CI", "CI", JOptionPane.ERROR_MESSAGE);
        } else {
            validaCI();
        }
    }//GEN-LAST:event_jBtnValidaCIMemoriaActionPerformed

    private void jBtnActualizarBaseDeDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarBaseDeDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnActualizarBaseDeDatoActionPerformed

    public void validaCI() {
        Scanner sc = new Scanner(System.in);
        String s = jTxtCIMemoria.getText();
        String calcula = "2987634";
        int total = 0;
        for (int i = 0; i < 7; i++) {
            int si = Integer.parseInt(s.substring(i, i + 1));
            int no = Integer.parseInt(calcula.substring(i, i + 1));
            total = total + (si * no);
        }
        int multiplo = 0;
        int digito = 0;
        multiplo = ((total / 10) * 10) + 10;
        digito = (multiplo - total);
        if (digito == Integer.parseInt(s.substring(7, 8))) {
            JOptionPane.showMessageDialog(this, "la Cedula de: " + " Es Correcta", "Validación C.I", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "la Cedula de: " + " Es Incorrecto");
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmEmpleado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarBaseDeDato;
    private javax.swing.JButton jBtnActualizarMemoria;
    private javax.swing.JButton jBtnEliminarFilaMemoria;
    private javax.swing.JButton jBtnEliminarTodoMemoria;
    private javax.swing.JButton jBtnGuardaEnBaseDeDato;
    private javax.swing.JButton jBtnGuardaEnLaTablar;
    private javax.swing.JButton jBtnValidaCIMemoria;
    private javax.swing.JButton jBtnValidaCIMemoria1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblMemoria;
    private javax.swing.JTable jTblMemoria1;
    private javax.swing.JTextField jTxtApellidoMemoria;
    private javax.swing.JTextField jTxtApellidoMemoria1;
    private javax.swing.JTextField jTxtCIMemoria;
    private javax.swing.JTextField jTxtDireccionMemoria;
    private javax.swing.JTextField jTxtDireccionMemoria1;
    private javax.swing.JTextField jTxtNombreMemoria;
    private javax.swing.JTextField jTxtNombreMemoria1;
    private javax.swing.JTextField jTxtTelefonoMemoria;
    private javax.swing.JTextField jTxtTelefonoMemoria1;
    // End of variables declaration//GEN-END:variables
}
