/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.Conexion;
import Controladores.Productos;
import IO.CodigoDeVelocidad;
import IO.IndiceDeCarga;
import IO.Proveedor;
import java.awt.Image;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Victor
 */
public class FrmProducto extends javax.swing.JFrame {

    DefaultComboBoxModel modelo = new DefaultComboBoxModel();
    DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
    DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();

    private byte[] fotoPerfil;
    private Object ControladorPrincipal;

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();

        cargarCombo();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtMedidaMemoria = new javax.swing.JTextField();
        jTxtModeloMemoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CboCodigoVelocidadMemoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jBtnGuardarEnTablaMemoria = new javax.swing.JButton();
        jBtnLimpiarCamposMemoria = new javax.swing.JButton();
        jBtnImagenesMemoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMemoria = new javax.swing.JTable();
        jBtnActualizarMemoria = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnEliminarTodoMemoria = new javax.swing.JButton();
        jBtnEliminarFilaMemoria = new javax.swing.JButton();
        jBtnGuardarEnBaseDeDatos = new javax.swing.JButton();
        jTxtPrecioMemoria = new javax.swing.JTextField();
        CboIndiceDeCargaMemoria = new javax.swing.JComboBox<>();
        jTxtMarcaMemoria = new javax.swing.JTextField();
        CboProveedorMemoria = new javax.swing.JComboBox<>();
        jTxtProductoMemoria = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLblImagenesMemoria = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTxtMedidaBaseDeDatos = new javax.swing.JTextField();
        CboIndiceDeCargaBaseDeDatos = new javax.swing.JComboBox<>();
        jBtnImagenesBaseDeDatos = new javax.swing.JButton();
        jBtnActualizarBaseDeDatos = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtProductoBaseDeDatos = new javax.swing.JTextField();
        jTxtMarcaBaseDeDatos = new javax.swing.JTextField();
        CboCodigoVelocidadBaseDeDatos = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTxtPrecioBaseDeDatos = new javax.swing.JTextField();
        jTxtModeloBaseDeDatos = new javax.swing.JTextField();
        CboProveedorBaseDeDatos = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLblImagenesBaseDeDatos = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Neumáticos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Nombre Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ruedas.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Medida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Modelo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jTxtMedidaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtMedidaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 200, -1));

        jTxtModeloMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtModeloMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 200, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Simbolo Velocidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        CboCodigoVelocidadMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CboCodigoVelocidadMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboCodigoVelocidadMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboCodigoVelocidadMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(CboCodigoVelocidadMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 200, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Foto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        jBtnGuardarEnTablaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardarEnTablaMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardarEnTablaMemoria.setText("Guardar en tabla");
        jBtnGuardarEnTablaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarEnTablaMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardarEnTablaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 222, 35));

        jBtnLimpiarCamposMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnLimpiarCamposMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        jBtnLimpiarCamposMemoria.setText("Limpiar campos");
        jPanel1.add(jBtnLimpiarCamposMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 222, 35));

        jBtnImagenesMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnImagenesMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes.png"))); // NOI18N
        jBtnImagenesMemoria.setText("Imagenes");
        jBtnImagenesMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImagenesMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnImagenesMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 222, 35));

        jTblMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Proveedor", "Medida", "Marca", "Modelo", "Ind.", "Simb."
            }
        ));
        jScrollPane1.setViewportView(jTblMemoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 866, 100));

        jBtnActualizarMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarMemoria.setText("Actualizar");
        jPanel1.add(jBtnActualizarMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 222, 35));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Precio U$S:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, -1, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Indice De Carga:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Marca:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Proveedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jBtnEliminarTodoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarTodoMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarTodoMemoria.setText("Eliminar todo");
        jPanel1.add(jBtnEliminarTodoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 222, 35));

        jBtnEliminarFilaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarFilaMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarFilaMemoria.setText("Eliminar fila");
        jPanel1.add(jBtnEliminarFilaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 222, 35));

        jBtnGuardarEnBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardarEnBaseDeDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardarEnBaseDeDatos.setText("Guardar en base de datos");
        jPanel1.add(jBtnGuardarEnBaseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 222, 35));

        jTxtPrecioMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtPrecioMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, 190, -1));

        CboIndiceDeCargaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CboIndiceDeCargaMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(CboIndiceDeCargaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 200, -1));

        jTxtMarcaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtMarcaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 200, -1));

        CboProveedorMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CboProveedorMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(CboProveedorMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 200, -1));

        jTxtProductoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtProductoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 200, -1));

        jLblImagenesMemoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblImagenesMemoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImagenesMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImagenesMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 205, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 610));

        jTabbedPane1.addTab("Agregar Producto", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel14.setText("Listado de neumáticos");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ruedas.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 220));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Neumatico", "Proveedor", "Medidas", "Marca", "Modelo", "IndeDeCarga", "SimboloVelocidad", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 850, 220));

        jTxtMedidaBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        CboIndiceDeCargaBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CboIndiceDeCargaBaseDeDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnImagenesBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnImagenesBaseDeDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes.png"))); // NOI18N
        jBtnImagenesBaseDeDatos.setText("Imagenes");

        jBtnActualizarBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarBaseDeDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarBaseDeDatos.setText("Actualizar");

        jCheckBox1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBox1.setText("Activo");

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel18.setText("Simbolo Velocidad:");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setText("Marca:");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setText("Nombre Producto:");

        jTxtProductoBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jTxtMarcaBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        CboCodigoVelocidadBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CboCodigoVelocidadBaseDeDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setText("Precio U$S:");

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setText("Modelo:");

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setText("Proveedor:");

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel24.setText("Foto:");

        jTxtPrecioBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jTxtModeloBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        CboProveedorBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CboProveedorBaseDeDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel23.setText("Indice De Carga:");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel22.setText("Medida:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImagenesBaseDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblImagenesBaseDeDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(619, 619, 619)
                        .addComponent(jLabel24)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnImagenesBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnActualizarBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(50, 50, 50)
                                .addComponent(jTxtProductoBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel19)
                                .addGap(36, 36, 36)
                                .addComponent(CboProveedorBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(125, 125, 125)
                                .addComponent(jTxtMarcaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel20)
                                .addGap(58, 58, 58)
                                .addComponent(jTxtModeloBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CboIndiceDeCargaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(98, 98, 98)
                                .addComponent(jTxtMedidaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(44, 44, 44)
                        .addComponent(CboCodigoVelocidadBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel21)
                        .addGap(31, 31, 31)
                        .addComponent(jTxtPrecioBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTxtProductoBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(CboProveedorBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTxtMedidaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CboIndiceDeCargaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtMarcaBaseDeDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTxtModeloBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel20)))
                            .addGap(3, 3, 3))))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel18))
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTxtPrecioBaseDeDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CboCodigoVelocidadBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jCheckBox1)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBtnImagenesBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnActualizarBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 1110, 240));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 610));

        jTabbedPane1.addTab("Actualizar Producto (Base De Datos)", jPanel2);

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarEnTablaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarEnTablaMemoriaActionPerformed
        // TODO add your handling code here:
//        IO.Producto p = new IO.Producto();
//        p.setCodigoDeVelocidades((CodigoDeVelocidad) CboCodigoVelocidadMemoria.getSelectedItem());
//        p.setIndiceDeCargas((IndiceDeCarga) CboIndiceDeCargaMemoria.getSelectedItem());
//        p.setProveedor((Proveedor) CboProveedorMemoria.getSelectedItem());
//        p.setNombreProducto(jTxtProductoMemoria.getText());
//        p.setMedida(jTxtMedidaMemoria.getText());
//        p.setMarca(jTxtMarcaMemoria.getText());
//        p.setModelo(jTxtModeloMemoria.getText());
//        p.setPrecio(jTxtPrecioMemoria.getText());
//        p.setFoto(jLblImagenesMemoria.getText().getBytes());
//        Conexion.getInstance().guardar(p);
    }//GEN-LAST:event_jBtnGuardarEnTablaMemoriaActionPerformed

    private void jLblImagenesMemoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblImagenesMemoriaMouseClicked
        // TODO add your handling code here:
        FrmVistaPrevia frm = new FrmVistaPrevia();
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_jLblImagenesMemoriaMouseClicked

    private void jBtnImagenesMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImagenesMemoriaActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes", "jpg", "gif", "png");
        jFileChooser1.setFileFilter(filter);
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                Image aux = new ImageIcon(jFileChooser1.getSelectedFile().getPath()).getImage();
                ImageIcon perfil = new ImageIcon(aux.getScaledInstance(100, 100, Image.SCALE_DEFAULT));
                jLblImagenesMemoria.setIcon(perfil);
                fotoPerfil = Conexion.getInstance().convertirImagen(jFileChooser1.getSelectedFile().getPath());
            } catch (IOException ex) {
            }
        }
//        jLblImagenesMemoria.setIcon(icon);
    }//GEN-LAST:event_jBtnImagenesMemoriaActionPerformed

    private void CboCodigoVelocidadMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboCodigoVelocidadMemoriaActionPerformed
        // TODO add your handling code here
//        if(CboCodigoVelocidadMemoria.getSelectedIndex() != - 1){
            
        
        if (CboCodigoVelocidadMemoria.getSelectedIndex() == CboCodigoVelocidadMemoria.getItemCount() - 1) {
            FrmCodigoDeVelocidad frm = new FrmCodigoDeVelocidad(this);
            frm.toFront();
            frm.setVisible(true);
//        }
        }
    }//GEN-LAST:event_CboCodigoVelocidadMemoriaActionPerformed

    public void cargarCombo(){
        modelo = new DefaultComboBoxModel();
        modelo.addElement("ELIJA OPCION");

        Iterator<IO.CodigoDeVelocidad> ItCodigoDeVelocidad = Conexion.getInstance().getCodigoDeVelocidades().ListCodigoDeVelocidad().iterator();
        while (ItCodigoDeVelocidad.hasNext()) {
            modelo.addElement(ItCodigoDeVelocidad.next());
        }
        modelo.addElement("Agregar Elemento");
        CboCodigoVelocidadMemoria.setModel(modelo);

        modelo1.addElement("ELIJA OPCION");

        Iterator<IO.IndiceDeCarga> ItIndiceDeCarga = Conexion.getInstance().getIndiceDeCargas().ListIndiceDeCarga().iterator();
        while (ItIndiceDeCarga.hasNext()) {
            modelo1.addElement(ItIndiceDeCarga.next());
        }
        CboIndiceDeCargaMemoria.setModel(modelo1);

        modelo2.addElement("ELIJA OPCION");

        Iterator<IO.Proveedor> ItProveedor = Conexion.getInstance().getProveedores().ListProveedor().iterator();
        while (ItProveedor.hasNext()) {
            modelo2.addElement(ItProveedor.next());
        }
        CboProveedorMemoria.setModel(modelo2);
        
        CboCodigoVelocidadMemoria.setSelectedIndex(-1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboCodigoVelocidadBaseDeDatos;
    private javax.swing.JComboBox<String> CboCodigoVelocidadMemoria;
    private javax.swing.JComboBox<String> CboIndiceDeCargaBaseDeDatos;
    private javax.swing.JComboBox<String> CboIndiceDeCargaMemoria;
    private javax.swing.JComboBox<String> CboProveedorBaseDeDatos;
    private javax.swing.JComboBox<String> CboProveedorMemoria;
    private javax.swing.JButton jBtnActualizarBaseDeDatos;
    private javax.swing.JButton jBtnActualizarMemoria;
    private javax.swing.JButton jBtnEliminarFilaMemoria;
    private javax.swing.JButton jBtnEliminarTodoMemoria;
    private javax.swing.JButton jBtnGuardarEnBaseDeDatos;
    private javax.swing.JButton jBtnGuardarEnTablaMemoria;
    private javax.swing.JButton jBtnImagenesBaseDeDatos;
    private javax.swing.JButton jBtnImagenesMemoria;
    private javax.swing.JButton jBtnLimpiarCamposMemoria;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblImagenesBaseDeDatos;
    private javax.swing.JLabel jLblImagenesMemoria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTblMemoria;
    private javax.swing.JTextField jTxtMarcaBaseDeDatos;
    private javax.swing.JTextField jTxtMarcaMemoria;
    private javax.swing.JTextField jTxtMedidaBaseDeDatos;
    private javax.swing.JTextField jTxtMedidaMemoria;
    private javax.swing.JTextField jTxtModeloBaseDeDatos;
    private javax.swing.JTextField jTxtModeloMemoria;
    private javax.swing.JTextField jTxtPrecioBaseDeDatos;
    private javax.swing.JTextField jTxtPrecioMemoria;
    private javax.swing.JTextField jTxtProductoBaseDeDatos;
    private javax.swing.JTextField jTxtProductoMemoria;
    // End of variables declaration//GEN-END:variables
}
