/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.Conexion;
import IO.IndiceDeCarga;
import IO.Proveedor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class FrmProveedor extends javax.swing.JFrame {

    ArrayList<Proveedor> lista = new ArrayList<Proveedor>();

    DefaultListModel modelo = new DefaultListModel();

    /**
     * Creates new form FrmProveedor
     */
    public FrmProveedor() {
        initComponents();
        
        Iterator<IO.Proveedor> ItProveedor = Conexion.getInstance().getProveedores().ListProveedor().iterator();

        while (ItProveedor.hasNext()) {

            modelo.addElement(ItProveedor.next());
        }
        
        this.setLocationRelativeTo(null);
        
        cargar();
        
        cerrar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtTelefonoMemoria = new javax.swing.JTextField();
        jTxtCompaniaMemoria = new javax.swing.JTextField();
        jTxtRutMemoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnGuardarEnLaTablaMemoria = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblMemoria = new javax.swing.JTable();
        jBtnValidaRutMemoria = new javax.swing.JButton();
        jTxtCantactoMemoria = new javax.swing.JTextField();
        jTxtDireccionMemoria = new javax.swing.JTextField();
        jBtnLimpiarCampoMemoria = new javax.swing.JButton();
        jBtnActualizarMemoria = new javax.swing.JButton();
        jBtnEliminarFilaMemoria = new javax.swing.JButton();
        jBtnEliminarTodoMemoria = new javax.swing.JButton();
        jBtnGuardarEnBaseDeDato = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBaseDeDatos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtTelefonoBaseDeDatos = new javax.swing.JTextField();
        jTxtCompaniaBaseDeDatos = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBtnActualizarBaseDeDatos = new javax.swing.JButton();
        jTxtDireccionBaseDeDatos = new javax.swing.JTextField();
        jTxtCantactoBaseDeDatos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Proveedores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Rut:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Nombre de compañia:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jTxtTelefonoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtTelefonoMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTelefonoMemoriaKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtTelefonoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 152, -1));

        jTxtCompaniaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtCompaniaMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCompaniaMemoriaKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtCompaniaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 152, -1));

        jTxtRutMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtRutMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtRutMemoriaKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtRutMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 152, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Nombre de contacto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Direccion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        jBtnGuardarEnLaTablaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardarEnLaTablaMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardarEnLaTablaMemoria.setText("Guardar en la tabla");
        jBtnGuardarEnLaTablaMemoria.setMaximumSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnLaTablaMemoria.setMinimumSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnLaTablaMemoria.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnLaTablaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarEnLaTablaMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardarEnLaTablaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 222, 35));

        jTblMemoria.setAutoCreateRowSorter(true);
        jTblMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTblMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre de compañia", "Nombre de contacto", "Telefono", "Direccion"
            }
        ));
        jTblMemoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblMemoriaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblMemoria);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 705, 100));

        jBtnValidaRutMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnValidaRutMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Validador.png"))); // NOI18N
        jBtnValidaRutMemoria.setText("Valida Rut");
        jBtnValidaRutMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValidaRutMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnValidaRutMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 222, 35));

        jTxtCantactoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtCantactoMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCantactoMemoriaKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtCantactoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 152, -1));

        jTxtDireccionMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTxtDireccionMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, 152, -1));

        jBtnLimpiarCampoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnLimpiarCampoMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        jBtnLimpiarCampoMemoria.setText("Limpiar campos");
        jBtnLimpiarCampoMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarCampoMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLimpiarCampoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 222, 35));

        jBtnActualizarMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarMemoria.setText("Actualizar");
        jBtnActualizarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnActualizarMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 222, 35));

        jBtnEliminarFilaMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarFilaMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarFilaMemoria.setText("Eliminar fila");
        jBtnEliminarFilaMemoria.setMaximumSize(new java.awt.Dimension(119, 25));
        jBtnEliminarFilaMemoria.setMinimumSize(new java.awt.Dimension(119, 25));
        jBtnEliminarFilaMemoria.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnEliminarFilaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarFilaMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEliminarFilaMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 222, 35));

        jBtnEliminarTodoMemoria.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnEliminarTodoMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jBtnEliminarTodoMemoria.setText("Eliminar todo");
        jBtnEliminarTodoMemoria.setMaximumSize(new java.awt.Dimension(119, 25));
        jBtnEliminarTodoMemoria.setMinimumSize(new java.awt.Dimension(119, 25));
        jBtnEliminarTodoMemoria.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnEliminarTodoMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarTodoMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEliminarTodoMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 222, 35));

        jBtnGuardarEnBaseDeDato.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnGuardarEnBaseDeDato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jBtnGuardarEnBaseDeDato.setText("Guardar en base de datos");
        jBtnGuardarEnBaseDeDato.setMaximumSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnBaseDeDato.setMinimumSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnBaseDeDato.setPreferredSize(new java.awt.Dimension(119, 25));
        jBtnGuardarEnBaseDeDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarEnBaseDeDatoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardarEnBaseDeDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 222, 35));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 580));

        jTabbedPane1.addTab("Agregar Provedor", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, -1));

        jTblBaseDeDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de compañia", "Nombre de contacto", "Telefono", "Direccion", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTblBaseDeDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblBaseDeDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblBaseDeDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 710, 200));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel15.setText("Listado de Proveedores");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Nombre de compañia:");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Telefono:");

        jTxtTelefonoBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtTelefonoBaseDeDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTelefonoBaseDeDatosKeyTyped(evt);
            }
        });

        jTxtCompaniaBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtCompaniaBaseDeDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCompaniaBaseDeDatosKeyTyped(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBox1.setText("Activo");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Direccion:");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("Nombre de contacto:");

        jBtnActualizarBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jBtnActualizarBaseDeDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        jBtnActualizarBaseDeDatos.setText("Actualizar");
        jBtnActualizarBaseDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarBaseDeDatosActionPerformed(evt);
            }
        });

        jTxtDireccionBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jTxtCantactoBaseDeDatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTxtCantactoBaseDeDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCantactoBaseDeDatosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(46, 46, 46)
                        .addComponent(jTxtCompaniaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)
                        .addGap(43, 43, 43)
                        .addComponent(jTxtCantactoBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(128, 128, 128)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(300, 300, 300)
                                .addComponent(jBtnActualizarBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTxtTelefonoBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel14)
                                .addGap(113, 113, 113)
                                .addComponent(jTxtDireccionBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addComponent(jTxtCompaniaBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addComponent(jTxtCantactoBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTxtTelefonoBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtDireccionBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnActualizarBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 710, 130));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.jpg"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 610));

        jTabbedPane1.addTab("Actualizar Provedor (Base De Datos)", jPanel2);

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtTelefonoMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTelefonoMemoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtTelefonoMemoriaKeyTyped

    private void jTxtCompaniaMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCompaniaMemoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtCompaniaMemoriaKeyTyped

    private void jTxtRutMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRutMemoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtRutMemoriaKeyTyped

    private void jBtnGuardarEnLaTablaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarEnLaTablaMemoriaActionPerformed
        // TODO add your handling code here:
        if (jTxtRutMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA RUT", "RUT", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtCompaniaMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA NOMBRE DE COMPAÑIA", "COMPAÑIA", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtCantactoMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA NOMBRE DE CONTACTO", "CONTACTO", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtTelefonoMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA TELEFONO", "TELEFONO", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtDireccionMemoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA DIRECCION", "DIRECCION", JOptionPane.ERROR_MESSAGE);
        } else {
            IO.Proveedor p = new IO.Proveedor();
            p.setRut(jTxtRutMemoria.getText());
            p.setNombreCompania(jTxtCompaniaMemoria.getText());
            p.setNombreContacto(jTxtCantactoMemoria.getText());
            p.setDireccion(jTxtDireccionMemoria.getText());
            p.setTelefono(jTxtTelefonoMemoria.getText());
            p.setActivo(true);
            lista.add(p);
            mostrar();
            iniPant();
        }
    }//GEN-LAST:event_jBtnGuardarEnLaTablaMemoriaActionPerformed

    private void jTblMemoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblMemoriaMouseClicked
        // TODO add your handling code here:
        int seleccion = jTblMemoria.rowAtPoint(evt.getPoint());
        jTxtRutMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 0)));
        jTxtCompaniaMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 1)));
        jTxtCantactoMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 2)));
        jTxtTelefonoMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 3)));
        jTxtDireccionMemoria.setText(String.valueOf(jTblMemoria.getValueAt(seleccion, 4)));
    }//GEN-LAST:event_jTblMemoriaMouseClicked

    private void jBtnValidaRutMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValidaRutMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnValidaRutMemoriaActionPerformed

    private void jTxtCantactoMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantactoMemoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtCantactoMemoriaKeyTyped

    private void jBtnLimpiarCampoMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarCampoMemoriaActionPerformed
        // TODO add your handling code here:
        int limpiarCampo = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE LIMPIAR LOS CAMPOS?", "LIMPIAR", JOptionPane.YES_NO_OPTION);
        if (limpiarCampo == JOptionPane.YES_OPTION) {
            iniPant();
        }
    }//GEN-LAST:event_jBtnLimpiarCampoMemoriaActionPerformed

    private void jBtnActualizarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarMemoriaActionPerformed
        // TODO add your handling code here:
        int filaSelec = jTblMemoria.getSelectedRow();
        if (filaSelec >= 0) {
            if (jTxtRutMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA RUT", "RUT", JOptionPane.ERROR_MESSAGE);
            } else if (jTxtCompaniaMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA NOMBRE DE COMPAÑIA", "COMPAÑIA", JOptionPane.ERROR_MESSAGE);
            } else if (jTxtCantactoMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA NOMBRE DE CONTACTO", "CONTACTO", JOptionPane.ERROR_MESSAGE);
            } else if (jTxtTelefonoMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA TELEFONO", "TELEFONO", JOptionPane.ERROR_MESSAGE);
            } else if (jTxtDireccionMemoria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "FALTA DIRECCION", "DIRECCION", JOptionPane.ERROR_MESSAGE);
            } else {
                int guardar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ACTUALIZAR?", "ACTUALIZAR", JOptionPane.YES_NO_OPTION);
                if (guardar == JOptionPane.YES_OPTION) {
                    IO.Proveedor p = lista.get(jTblMemoria.getSelectedRow());
                    p.setRut(jTxtRutMemoria.getText());
                    p.setNombreCompania(jTxtCompaniaMemoria.getText());
                    p.setNombreContacto(jTxtCantactoMemoria.getText());
                    p.setDireccion(jTxtDireccionMemoria.getText());
                    p.setTelefono(jTxtTelefonoMemoria.getText());
                    mostrar();
                    JOptionPane.showMessageDialog(this, "A ACTUALIZADO CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                    iniPant();
                } else {
                    JOptionPane.showMessageDialog(this, "ACTUALIZACION CANCELADA");
                    jTxtRutMemoria.requestFocus();
                    iniPant();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO A SELECCIONADO NINGUNA FILA", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnActualizarMemoriaActionPerformed

    private void jBtnEliminarFilaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarFilaMemoriaActionPerformed
        // TODO add your handling code here:
        int filaSelec = jTblMemoria.getSelectedRow();
        if (filaSelec >= 0) {
            int borrarFila = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ELIMINIAR LA FILA SELECCIONADA?", "ELIMINAR", JOptionPane.YES_NO_OPTION);
            if (borrarFila == JOptionPane.YES_OPTION) {
                lista.remove(jTblMemoria.getSelectedRow());
                if (jTblMemoria.getSelectedRow() != -1) {
                    DefaultTableModel mdl = (DefaultTableModel) jTblMemoria.getModel();
                    mdl.removeRow(jTblMemoria.getSelectedRow());
                    iniPant();
                    JOptionPane.showMessageDialog(this, "FILA ELIMINADA CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "ELIMINACION CANCELADA");
                iniPant();
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO A SELECCIONADO NINGUNA FILA");
        }
    }//GEN-LAST:event_jBtnEliminarFilaMemoriaActionPerformed

    private void jBtnEliminarTodoMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarTodoMemoriaActionPerformed
        // TODO add your handling code here:
        if (jTblMemoria.getRowCount() > 0) {
            int borrarTodo = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ELIMINAR TODO?", "ELIMINAR", JOptionPane.YES_NO_OPTION);
            if (borrarTodo == JOptionPane.YES_OPTION) {
                vaciadoMemoria();
                iniPant();
            }
        }
    }//GEN-LAST:event_jBtnEliminarTodoMemoriaActionPerformed

    private void jBtnGuardarEnBaseDeDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarEnBaseDeDatoActionPerformed
        // TODO add your handling code here:
        if (jTblMemoria.getRowCount() > 0) {
            int guardar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE GUARDAR EN LA BASE DE DATOS?", "GUARDAR", JOptionPane.YES_NO_OPTION);
            if (guardar == JOptionPane.YES_OPTION) {
                for (int i = 0; i < jTblMemoria.getRowCount(); i++) {
                    IO.Proveedor p = new IO.Proveedor();
                    p.setRut((String) jTblMemoria.getValueAt(i, 0));
                    p.setNombreCompania((String) jTblMemoria.getValueAt(i, 1));
                    p.setNombreContacto((String) jTblMemoria.getValueAt(i, 2));
                    p.setTelefono((String) jTblMemoria.getValueAt(i, 3));
                    p.setDireccion((String) jTblMemoria.getValueAt(i, 4));
                    p.setActivo(true);
                    Conexion.getInstance().guardar(p);
                }
                JOptionPane.showMessageDialog(this, "A GUARDADO CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                vaciadoMemoria();
                vaciadoBaseDeDato();
                Iterator<IO.Proveedor> ItProveedor = Conexion.getInstance().getProveedores().ListProveedor().iterator();
                
                while (ItProveedor.hasNext()) {

                    modelo.addElement(ItProveedor.next());
                }
                cargar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HAY DATOS EN LA TABLA", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnGuardarEnBaseDeDatoActionPerformed

    private void jTblBaseDeDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBaseDeDatosMouseClicked
        // TODO add your handling code here:
        int seleccion = jTblBaseDeDatos.rowAtPoint(evt.getPoint());
        jTxtCompaniaBaseDeDatos.setText(String.valueOf(jTblBaseDeDatos.getValueAt(seleccion, 0)));
        jTxtCantactoBaseDeDatos.setText(String.valueOf(jTblBaseDeDatos.getValueAt(seleccion, 1)));
        jTxtTelefonoBaseDeDatos.setText(String.valueOf(jTblBaseDeDatos.getValueAt(seleccion, 2)));
        jTxtDireccionBaseDeDatos.setText(String.valueOf(jTblBaseDeDatos.getValueAt(seleccion, 3)));
        jCheckBox1.setSelected((boolean) jTblBaseDeDatos.getValueAt(seleccion, 4));
    }//GEN-LAST:event_jTblBaseDeDatosMouseClicked

    private void jTxtTelefonoBaseDeDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTelefonoBaseDeDatosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtTelefonoBaseDeDatosKeyTyped

    private void jTxtCompaniaBaseDeDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCompaniaBaseDeDatosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtCompaniaBaseDeDatosKeyTyped

    private void jTxtCantactoBaseDeDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantactoBaseDeDatosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTxtCantactoBaseDeDatosKeyTyped

    private void jBtnActualizarBaseDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarBaseDeDatosActionPerformed
        if (jTxtCompaniaBaseDeDatos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA NOMBRE DE COMPAÑIA", "COMPAÑIA", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtCantactoBaseDeDatos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA NOMBRE DE CONTACTO", "CONTACTO", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtTelefonoBaseDeDatos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA TELEFONO", "TELEFONO", JOptionPane.ERROR_MESSAGE);
        } else if (jTxtDireccionBaseDeDatos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "FALTA DIRECCION", "DIRECCION", JOptionPane.ERROR_MESSAGE);
        } else {
            int actualizar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE ACTUALIZAR?", "ACTUALIZAR", JOptionPane.YES_NO_OPTION);
            if (actualizar == JOptionPane.YES_OPTION) {
                IO.Proveedor p = (IO.Proveedor) modelo.get(jTblBaseDeDatos.getSelectedRow());
                p.setNombreCompania(jTxtCompaniaBaseDeDatos.getText());
                p.setNombreContacto(jTxtCantactoBaseDeDatos.getText());
                p.setTelefono(jTxtTelefonoBaseDeDatos.getText());
                p.setDireccion(jTxtDireccionBaseDeDatos.getText());
                p.setActivo(jCheckBox1.isSelected());
                Conexion.getInstance().getProveedores().actualizar(p);
                modelo.remove(jTblBaseDeDatos.getSelectedRow());
                if (jTblBaseDeDatos.getRowCount() > 0) {
                    DefaultTableModel mdl = (DefaultTableModel) jTblBaseDeDatos.getModel();
                    modelo.clear();
                    mdl.setRowCount(0);
                    jTxtCompaniaBaseDeDatos.setText("");
                    jTxtCantactoBaseDeDatos.setText("");
                    jTxtTelefonoBaseDeDatos.setText("");
                    jTxtDireccionBaseDeDatos.setText("");
                    jCheckBox1.setSelected(false);
                    Iterator<IO.Proveedor> ItProveedor = Conexion.getInstance().getProveedores().ListProveedor().iterator();

                    while (ItProveedor.hasNext()) {

                        modelo.addElement(ItProveedor.next());
                    }
                    cargar();
                    JOptionPane.showMessageDialog(this, "A ACTUALIZADO CORRECTAMENTE", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            }else {
                JOptionPane.showMessageDialog(this, "ACTUALIZACION CANCELADA");
                jTxtCompaniaBaseDeDatos.setText("");
                jTxtCantactoBaseDeDatos.setText("");
                jTxtTelefonoBaseDeDatos.setText("");
                jTxtDireccionBaseDeDatos.setText("");
            }
        }
    }//GEN-LAST:event_jBtnActualizarBaseDeDatosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (jTblMemoria.getRowCount() < 1) {
            int cerrar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE CERRAR?", "CERRAR", JOptionPane.YES_NO_OPTION);
            if (cerrar == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO A GUARDADO EN LA BASE DE DATOS", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
            jBtnGuardarEnBaseDeDato.requestFocus();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void mostrar() {
        String matris[][] = new String[lista.size()][5];
        for (int i = 0; i < lista.size(); i++) {
            matris[i][0] = lista.get(i).getRut();
            matris[i][1] = lista.get(i).getNombreCompania();
            matris[i][2] = lista.get(i).getNombreContacto();
            matris[i][3] = lista.get(i).getTelefono();
            matris[i][4] = lista.get(i).getDireccion();
        }
        jTblMemoria.setModel(new javax.swing.table.DefaultTableModel(
                matris,
                new String[]{
                    "Rut", "Nombre de compañia", "Nombre de contacto", "Telefono", "Direccion"
                }
        ));
    }

    public void cargar() {
        DefaultTableModel mdl = (DefaultTableModel) jTblBaseDeDatos.getModel();
        Iterator<IO.Proveedor> ItProveedor = Conexion.getInstance().getProveedores().ListProveedor().iterator();
        while (ItProveedor.hasNext()) {
            Object[] fila = new Object[5];
            Proveedor aux = ItProveedor.next();
            fila[0] = aux;
            fila[1] = aux.getNombreContacto();
            fila[2] = aux.getTelefono();
            fila[3] = aux.getDireccion();
            fila[4] = aux.isActivo();
            mdl.addRow(fila);
          jTblBaseDeDatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        }
    }

    public void vaciadoMemoria() {
        DefaultTableModel mdl = (DefaultTableModel) jTblMemoria.getModel();
        lista.clear();
        mdl.setRowCount(0);
    }

    public void vaciadoBaseDeDato() {
        DefaultTableModel mdl = (DefaultTableModel) jTblMemoria.getModel();
        lista.clear();
        mdl.setRowCount(0);
    }
    
    public void iniPant() {
        jTxtRutMemoria.setText("");
        jTxtCompaniaMemoria.setText("");
        jTxtCantactoMemoria.setText("");
        jTxtTelefonoMemoria.setText("");
        jTxtDireccionMemoria.setText("");
        jTxtRutMemoria.requestFocus();
    }
    
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            this.setVisible(true);;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void confirmarSalida() {
        if (jTblMemoria.getRowCount() < 1) {
            int cerrar = JOptionPane.showConfirmDialog(this, "SEGURO QUIERE CERRAR?", "CERRAR", JOptionPane.YES_NO_OPTION);
            if (cerrar == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO A GUARDADO EN LA BASE DE DATOS", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
            jBtnGuardarEnBaseDeDato.requestFocus();
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmProveedor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarBaseDeDatos;
    private javax.swing.JButton jBtnActualizarMemoria;
    private javax.swing.JButton jBtnEliminarFilaMemoria;
    private javax.swing.JButton jBtnEliminarTodoMemoria;
    private javax.swing.JButton jBtnGuardarEnBaseDeDato;
    private javax.swing.JButton jBtnGuardarEnLaTablaMemoria;
    private javax.swing.JButton jBtnLimpiarCampoMemoria;
    private javax.swing.JButton jBtnValidaRutMemoria;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblBaseDeDatos;
    private javax.swing.JTable jTblMemoria;
    private javax.swing.JTextField jTxtCantactoBaseDeDatos;
    private javax.swing.JTextField jTxtCantactoMemoria;
    private javax.swing.JTextField jTxtCompaniaBaseDeDatos;
    private javax.swing.JTextField jTxtCompaniaMemoria;
    private javax.swing.JTextField jTxtDireccionBaseDeDatos;
    private javax.swing.JTextField jTxtDireccionMemoria;
    private javax.swing.JTextField jTxtRutMemoria;
    private javax.swing.JTextField jTxtTelefonoBaseDeDatos;
    private javax.swing.JTextField jTxtTelefonoMemoria;
    // End of variables declaration//GEN-END:variables
}
